<?php

return array(
  'name' => 'btHost',
  'description' => '虚拟主机管理系统，完美的解决您的需求，多种多样的使用场景',
  'logo' => '/logo.png',
  'beian' => '',
  'timezone' => 'Asia/Shanghai',
  'cdnurl' => '',
  'version' => '1.0.1',
  'languages' =>
  array(
    'backend' => 'zh-cn',
    'frontend' => 'zh-cn',
  ),
  'forbiddenip' => '',
  'configgroup' =>
  array(
    'basic' => 'Basic',
    'email' => 'Email',
    'server' => 'Server',
    'config' => 'Config',
    'secret' => 'Secret',
    'domain' => 'Domain',
    'notice' => 'Notice',
    'dictionary' => 'Dictionary',
    'personalization' => 'Personalization',
  ),
  'mail_type' => '1',
  'mail_smtp_host' => 'smtp.qq.com',
  'mail_smtp_port' => '465',
  'mail_smtp_user' => '10000',
  'mail_smtp_pass' => 'password',
  'mail_verify_type' => '2',
  'mail_from' => '10000@qq.com',
  'email' => '',
  'ftqq_sckey' => '',
  'access_token' => '',
  'api_returnip' => '',
  'queue_key' => 'dA0IwO',
  'expire_action' => 'recycle',
  'recycle_delete' => '7',
  'api_token' => '',
  'api_port' => '8888',
  'excess_panel' => '0',
  'main_center_notice' => '',
  'main_left_notice' => '',
  'main_right_notice' => '',
  'public_head_notice' => '',
  'iframe_cache' => 'false',
  'console_css' => '',
  'console_head' => '',
  'console_foot' => '',
  'login_bg' => '/static/images/login-bg1.jpg',
  'ftp_server' => '',
  'ftp_port' => '21',
  'ftp_type' => 'true',
  'dnspod_analysis_type' => 'A',
  'dnspod_analysis_url' => '',
  'default_analysis' => '0',
  'analysis_desc' => '',
  'split_size' => '10',
  'fixedpage' => 'dashboard',
  'phpmyadmin' => '',
  'debug' => '0',
  'status' => '0',
  'http' => 'http://',
  'auto_flow' => '1',
  'auto_update' => '1',
  'auto_notice' => '1',
);
