<?php

return array (
  'name' => 'btHost',
  'description' => '虚拟主机管理系统，完美的解决您的需求，多种多样的使用场景',
  'logo' => '/logo.png',
  'beian' => '',
  'timezone' => 'Asia/Shanghai',
  'cdnurl' => '',
  'version' => '1.0.1',
  'languages' => 
  array (
    'backend' => 'zh-cn',
    'frontend' => 'zh-cn',
  ),
  'forbiddenip' => '',
  'configgroup' => 
  array (
    'basic' => 'Basic',
    'email' => 'Email',
    'server' => 'Server',
    'config' => 'Config',
    'secret' => 'Secret',
    'domain' => 'Domain',
    'notice' => 'Notice',
    'dictionary' => 'Dictionary',
    'personalization' => 'Personalization',
  ),
  'mail_type' => '1',
  'mail_smtp_host' => 'smtp.qq.com',
  'mail_smtp_port' => '465',
  'mail_smtp_user' => '10000',
  'mail_smtp_pass' => 'password',
  'mail_verify_type' => '2',
  'mail_from' => '10000@qq.com',
  'email' => '',
  'ftqq_sckey' => '',
  'access_token' => '0VWx31Gd2kc5',
  'api_returnip' => '',
  'queue_key' => 'dA0IwO',
  'expire_action' => 'recycle',
  'recycle_delete' => '7',
  'api_token' => 'b816rlXz2-4N_NlGgnh4_K5Rw5AYLSgMOQrFijrSYXaqPwswyyweXwCl-uSEOpIFUaM_3_MZuKmciUumyA',
  'api_port' => '8888',
  'excess_panel' => '0',
  'main_center_notice' => '',
  'main_left_notice' => '',
  'main_right_notice' => '',
  'public_head_notice' => '',
  'iframe_cache' => 'true',
  'console_css' => '',
  'console_head' => '',
  'console_foot' => '',
  'login_bg' => '/static/images/login-bg1.jpg',
  'ftp_server' => '192.168.191.129',
  'ftp_port' => '21',
  'dnspod_analysis_type' => 'A',
  'dnspod_analysis_url' => '192.168.191.129',
  'default_analysis' => '0',
  'analysis_desc' => '',
  'split_size' => '10',
  'authCode' => '8969zEyQNlc0-xPTXeArN-I2asEonET_nimFI4HYM3RokqM',
  'fixedpage' => 'dashboard',
  'phpmyadmin' => 'http://192.168.191.129:888/phpmyadmin_2b42747a02485e2d',
);