<?php

return array (
  'name' => 'btHost',
  'beian' => '',
  'cdnurl' => '',
  'version' => '1.0.1',
  'timezone' => 'Asia/Shanghai',
  'forbiddenip' => '',
  'languages' => 
  array (
    'backend' => 'zh-cn',
    'frontend' => 'zh-cn',
  ),
  'fixedpage' => 'dashboard',
  'configgroup' => 
  array (
    'basic' => 'Basic',
    'email' => 'Email',
    'server' => 'Server',
    'config' => 'Config',
    'secret' => 'Secret',
    'notice' => 'Notice',
    'dictionary' => 'Dictionary',
  ),
  'mail_type' => '1',
  'mail_smtp_host' => 'smtp.qq.com',
  'mail_smtp_port' => '465',
  'mail_smtp_user' => '10000',
  'mail_smtp_pass' => 'password',
  'mail_verify_type' => '2',
  'mail_from' => '10000@qq.com',
  'email' => '',
  'ftqq_sckey' => '',
  'access_token' => '0VWx31Gd2kc5',
  'api_returnip' => '',
  'que_key' => 'dA0IwO',
  'expire_action' => 'recycle',
  'recycle_delete' => '7',
  'phpmyadmin' => 'http://192.168.191.129:888/phpmyadmin_2b42747a02485e2d',
  'api_token' => '00nL2eLQCxDfk06AQ15w1VQ93O3A94HV',
  'excess_panel' => '0',
  'main_center_notice' => '',
  'main_left_notice' => '',
  'main_right_notice' => '',
  'public_head_notice' => '',
  'iframe_cache' => 'true',
  'console_css' => '',
  'console_head' => '',
  'console_foot' => '',
  'ftp_server' => '192.168.191.129',
  'ftp_port' => '21',
);